jobs:
- job: MacOS_CI
  displayName: 'MacOS CI'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix: 
      Py27:
        python_version: '2.7.16'
        python_pkg: 'python-2.7.16-macosx10.9.pkg'
        python: 'python2.7'
      Py36:
        python_version: '3.6.8'
        python_pkg: 'python-3.6.8-macosx10.9.pkg'
        python: 'python3.6'
      Py37:
        python_version: '3.7.3'
        python_pkg: 'python-3.7.3-macosx10.9.pkg'
        python: 'python3.7'
      Py38:
        python_version: '3.8.0'
        python_pkg: 'python-3.8.0-macosx10.9.pkg'
        python: 'python3.8'
    maxParallel: 4


  variables: {'PYTHONUNBUFFERED': '1'}

  steps:
  - checkout: self
    submodules: recursive

  - script: |
      curl -O https://www.python.org/ftp/python/$PYTHON_VERSION/$PYTHON_PKG
      sudo installer -pkg $PYTHON_PKG -target /
      which $PYTHON
      $PYTHON --version
    displayName: 'Fetch Python'

  - script: |
      curl -O https://bootstrap.pypa.io/get-pip.py
      $PYTHON get-pip.py
      $PYTHON -m pip install -U setuptools wheel 
      $PYTHON -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      #sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
      xcode-select --print-path
      $PYTHON build.py --jobs=4 build_wx
    displayName: 'build wxWidgets'

  - script: |
      $PYTHON build.py dox etg --nodoc sip
    displayName: 'generate code'

  - script: |
      $PYTHON build.py --jobs=4 build_py
    displayName: 'build wxPython'

  - script: |
      $PYTHON build.py bdist_wheel
      $PYTHON build.py install
      $PYTHON -c "import wx; print(wx.version());"
    displayName: 'build wheel and test install'
